server:
  port: 7790
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8894
        port: 8719
  devtools:
    livereload:
      port: 35730
#  cloud:
#    gateway:
#      routes:
#        - id: fund
#          uri: http://localhost:7799
#          predicates:
#            - Path=/api/**